### ISSUE TITLE
Support multi monitors

### ISSUE THREAD

**Issue by takaxp** [takaxp/moom#12]

**Comment by yuanzhhh** [comment]
mark

**Comment by takaxp** [comment]
Version 1.3.15 supports multi monitors on macOS (NS build only).
To enable the feature, please configure `moom-multi-monitors-support`. For example,

```
(setq moom-multi-monitors-support t)
(moom-mode 1)
```

The `moom-move-frame-right` and `moom-move-frame-left` are the triggers to identify which monitor you are going to mainly use. So if you use two monitors left and right side, please move Emacs frame by `moom-move-frame-right` or `moom-move-frame-left`, then `moom.el` will automatically identify the current monitor. If you move the frame by mouse, then please call `M-x moom-identify-current-monitor` by yourself.

The feature that are currently implemented has been tested in my environment using two HD monitors.

NOTE1: `moom-move-frame-right` and `moom-move-frame-left` can jump from one monitor to another on macOS. For other system, you can only use mouse to jump between monitors. And unfortunately I didn't test such scenario, but hopefully I'll try.

NOTE2: ~~The current implementation assumes that the second display is located the right side of the main display. If you swap the displays, i.e. put the second display to the left side of the main display, `moom.el` will be broken. This should be fixed in future.~~
**Supported from Version 1.3.28!** (but only for macOS NS build)
**Supported from Version 1.3.31!** (for macOS both NS build and EMP build)
**Supported from Version 1.3.34!** (for Windows 10)
**Supported from Version 1.4.1!** (for Ubuntu 20.04)
