### ISSUE TITLE
Default frame size and position

### ISSUE THREAD

**Issue by emenel** [takaxp/moom#24]
Is there a moom-friendly way to set the initial/default frame size and position? 

Right now I'm running this right before initializing moom-mode in my init:

```
    (set-frame-width (selected-frame) 150)
    (set-frame-height (selected-frame) 48)
```

But when `(moom-mode 1)` runs after that it changes the frame size.

In addition, when I try to run `(moom-move-frame-to-center)` in my config after loading moom it doesn't seem to do anything, nor is there an error.

Thanks for any assistance! (love this package!)

**Comment by takaxp** [comment]
Could you try the following code in your config?

```
(defun my-moom-default-frame-size ()
  (set-frame-width (selected-frame) 150)
  (set-frame-height (selected-frame) 48)
  (moom-move-frame-to-center))
(add-hook 'moom-mode-hook #'my-moom-default-frame-size)
```

**Comment by emenel** [comment]
Thank you for that! 

That code seems to work. I'm also using Doom, so it took a bit to figure out how to put this in the proper loading sequence so that it runs at the right time... but after loading moom using the `(load-package!)` macro and using the `:after-call` hook this is working great.

For anyone else that might end up here and is using Doom emacs, this is the working code from my config.el:

```
(use-package! moom
  :load-path "replace with your path to moom"
  :after-call doom-after-init-hook
  :config
  (setq moom-use-font-module nil)
  (moom-recommended-keybindings '(all wof))
  (setq moom-user-margin '(50 50 50 50))
  (setq moom-command-with-centering '(single double delete split))
  (when (display-graphic-p)
    (defun my-moom-default-frame-size ()
      (set-frame-width (selected-frame) 150)
      (set-frame-height (selected-frame) 48)
      (moom-move-frame-to-center))
    (add-hook! 'moom-mode-hook #'my-moom-default-frame-size)
    (moom-mode 1)
  )
)
```

**Comment by takaxp** [comment]
Thanks! I'll create a support page in GitHub wiki that includes your example.

**Comment by emenel** [comment]
Unfortunately this has stopped working. It works if I remove the `(moom-mode 1)` call from the `use-package!` block, and then call `moom-mode` manually once emacs has loaded. I have yet to track down why ... but something in the placement of that call isn't working with recent updates.
