### ISSUE TITLE
(setq moom-fill-left t) don't work

### ISSUE THREAD

**Issue by jjibagar** [takaxp/moom#27]
I'm trying to get it to start with the option moom-fill-left t but it doesn't work, it doesn't give an error or do anything. However if I use the command with M-x it does work.
My code
```
(when (require 'moom nil t)
  (setq moom-fill-left t)
  (moom-mode 1))
```

**Comment by takaxp** [comment]
Well, `moom-fill-left` is not a variable so the second line of your code do nothing for filling your screen.

**Comment by jjibagar** [comment]
True, my fault.
I have been testing so that the font size does not change with moom-use -font-module-nil and I have managed to get it to work with:

```
(when (require 'moom nil t)
  (setq moom-use-font-module nil)
  (moom-mode 1))

 (with-eval-after-load "moom"
   (moom-fill-left)
   (moom-mode 1))
```
